[package]
name = "kademlia"
version = "0.1.0"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>"]
license = "GPL-3"

[dependencies]
bincode = "0.7"
log = "0.3"
env_logger = "0.3"
rand = "0.3"
serde = "0.9"
serde_derive = "0.9"
futures = "0.1"
